# Server port binding settings.
server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
